Failure # 1 (occurred at 2020-01-22_11-44-02)
Traceback (most recent call last):
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 426, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 378, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/worker.py", line 1457, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray_worker[39m (pid=9413, ip=192.168.0.11)
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_task.function_executor
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 444, in train
    raise e
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 433, in train
    result = Trainable.train(self)
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 140, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/rllib/optimizers/rollout.py", line 29, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray_worker[39m (pid=9412, ip=192.168.0.11)
  File "python/ray/_raylet.pyx", line 627, in ray._raylet.execute_task
  File "/home/alexandre/.conda/envs/XRL/lib/python3.6/site-packages/ray/memory_monitor.py", line 130, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node alexandre-lenovo is used (7.23 / 7.61 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
9413	1.47GiB	/home/alexandre/.conda/envs/XRL/bin/python /home/alexandre/.conda/envs/XRL/lib/python3.6/site-packag
9412	0.69GiB	/home/alexandre/.conda/envs/XRL/bin/python /home/alexandre/.conda/envs/XRL/lib/python3.6/site-packag
9415	0.69GiB	/home/alexandre/.conda/envs/XRL/bin/python /home/alexandre/.conda/envs/XRL/lib/python3.6/site-packag
9414	0.67GiB	/home/alexandre/.conda/envs/XRL/bin/python /home/alexandre/.conda/envs/XRL/lib/python3.6/site-packag
9380	0.61GiB	python working_multiagent_google.py
1386	0.15GiB	/usr/bin/plasmashell
1707	0.14GiB	/snap/code/23/usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --f
1692	0.11GiB	/snap/code/23/usr/share/code/code --type=gpu-process --field-trial-handle=13195790676990217569,16633
1759	0.08GiB	/snap/code/23/usr/share/code/code --inspect-port=0 /snap/code/23/usr/share/code/resources/app/out/bo
1372	0.05GiB	/usr/bin/kwin_x11 -session 101951761ab1be000157959469300000012580022_1579609476_341090

In addition, up to 1.39 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray, and the max Redis size with `redis_max_memory`. Note that Ray assumes all system memory is available for use by workers. If your system has other applications running, you should manually set these memory limits to a lower value.

